### ISSUE TITLE
Introduce Google Maps API

### ISSUE THREAD

**Issue by matthewdeguzman** [matthewdeguzman/GatorGuessr#24]
I'm not sure what API or SKD we will use to implement the functionality of the game itself, but we should start implementing that within this sprint. The login page has taken a bit too long, so we shouldn't lag behind.

**Comment by matthewdeguzman** [comment]
Consider factors such as displaying minimap, ui for clicking on map, calculating score, displaying score, etc.

**Comment by matthewdeguzman** [comment]
Narrow down streetview to gainesville

**Comment by ramawama** [comment]
I have successfully introduced google maps API into the project, restricting it to Gainesville. I have also displayed the street view side by side. It can do it with some visual enhancements, but that is a separate issue. Functionality is there.
