### ISSUE TITLE
Add API authentication via proxy server

### ISSUE THREAD

**Issue by matthewdeguzman** [matthewdeguzman/GatorGuessr#27]
The API currently has no authentication, so anyone can access it which is a vulnerability as it leaves the server open for DDOS attacks. We should use [oauth2](https://pkg.go.dev/golang.org/x/oauth2) to provide proper authentication. There are various [tutorials](https://tutorialedge.net/golang/go-oauth2-tutorial/) to get familiar with the package.

**Comment by Coomesicle** [comment]
See JWT issue
