### ISSUE TITLE
Backend: CORS Requests fails on Frontend

### ISSUE THREAD

**Issue by Coomesicle** [matthewdeguzman/GatorGuessr#34]
I make HTTP request and it fails because CORS

**Comment by matthewdeguzman** [comment]
Intern doesn't know how to do a rest api call.. typical

**Comment by Coomesicle** [comment]
The issue was just not fixed

**Comment by Coomesicle** [comment]
Stephen (Senior Developer at 2 componies) (with his amazing brain) fixed the issue 😎
